/*
 *  Copyright (C) 2026 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include <string.h>
#include <position_sense/endat3/include/endat3_drv.h>
#include <drivers/hw_include/hw_types.h>
#include <drivers/hw_include/cslr_icss.h>
#include <kernel/dpl/ClockP.h>
#include <kernel/dpl/SystemP.h>
#include <kernel/dpl/DebugP.h>
#include <stdint.h>
#include <stddef.h>

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

#define ENDAT3_CRC_POLY    0x1A7
#define ENDAT3_CRC_INIT    0xFF

#define ENDAT3_PREAMBLE_SIZE 4
#define ENDAT3_PREAMBLE_PATTERN {0xCC, 0xCD, 0x94, 0x01}

/* EnDAT3 Memory Map Offsets for Load Share Mode
 * RTU_PRU core:   0x0000 - 0x06FF
 * PRU core:       0x0700 - 0x0DFF
 * TX_PRU core:    0x0E00 - 0x1500
 */
#define DMEM_BASE_OFFSET_RTU_PRU    0x0000
#define DMEM_BASE_OFFSET_PRU        0x0700
#define DMEM_BASE_OFFSET_TX_PRU     0x0E00

/* Maximum TX frames supported, limit is TX_BUFFER_SIZE/4 = 6 frames */
#define ENDAT3_MAX_TX_FRAMES        (TX_BUFFER_SIZE / 4)

/* ========================================================================== */
/*                           External Declarations                            */
/* ========================================================================== */

/**
 * \brief Number of EnDAT3 instances configured (generated by SysConfig)
 */
extern uint32_t gEndat3ConfigNum;

/**
 * \brief Array of EnDAT3 configuration handles (generated by SysConfig)
 */
extern endat3_config gEndat3Handle[];

/* ========================================================================== */
/*                          Constant Definitions                              */
/* ========================================================================== */

/**
 * \brief Default EnDAT3 initialization parameters
 *
 * \details Provides default values for endat3_params structure.
 *          Use endat3_params_init() to copy these defaults to a params structure.
 */
const endat3_params gEndat3DefaultParams =
{
    .pruicss_handle = NULL,
};

/* ========================================================================== */
/*                       Function Declarations                                */
/* ========================================================================== */

/* External function defined in endat3_lut.c */
extern void endat3_generate_memory_image(endat3_handle handle);

/* Static internal functions */
static int32_t endat3_calculate_clock(endat3_handle handle, endat3_clock_config *clk_cfg);
static int32_t endat3_config_clock(endat3_handle handle, endat3_clock_config *clk_cfg);
static int32_t endat3_set_delay_cycles(endat3_handle handle);
static int32_t endat3_set_channel_mask(endat3_handle handle, uint8_t channel_mask);
static int32_t endat3_config_clr_cfg0(endat3_handle handle);
static uint16_t endat3_reflect_general(uint16_t value, uint16_t width);
static uint16_t endat3_compute_crc(const volatile uint8_t *bytes, size_t length, uint16_t poly, uint16_t crcsize, uint16_t initialValue, uint8_t inputReflected, uint8_t resultReflected, uint16_t finalXor);
static uint8_t endat3_calculate_crc(const volatile uint8_t *data, uint32_t len);
static int32_t endat3_validate_crc(const volatile uint8_t *buffer, uint32_t length);
static int32_t endat3_prepare_request(endat3_handle handle, uint8_t cmd, volatile uint32_t *data_array, uint8_t num_frames);
static int32_t endat3_wait_rx_complete(endat3_handle handle);
static int32_t endat3_parse_frames(endat3_handle handle, volatile uint8_t *rx_buffer);
static int32_t endat3_config_iep_base_address(endat3_handle handle, uint32_t iep_base_address);

/* ========================================================================== */
/*                          Function Definitions                              */
/* ========================================================================== */

/* ========================================================================== */
/*                      Initialization and Configuration APIs                 */
/* ========================================================================== */

void endat3_params_init(endat3_params *params)
{
    if(params == NULL)
    {
        return;
    }

    /* Copy default parameters */
    *params = gEndat3DefaultParams;
}

endat3_handle endat3_init(uint32_t index, const endat3_params *params)
{
    int32_t             status = ENDAT3_SUCCESS;
    endat3_handle       handle = NULL;
    endat3_priv         *priv = NULL;
    const endat3_attrs  *attrs = NULL;
    endat3_clock_config clk_cfg;
    void                *base_addr = NULL;
    uint32_t            temp;

    /* Index and params validation */
    if((index >= gEndat3ConfigNum) || (params == NULL))
    {
        status = ENDAT3_ERR_INVALID_INPUT;
    }

    if(status == ENDAT3_SUCCESS)
    {
        handle = &gEndat3Handle[index];

        /* Get the pointer to the priv and attrs */
        priv = handle->priv;
        attrs = handle->attrs;

        /* Validate internal structures */
        if(priv == NULL || attrs == NULL)
        {
            /* Invalid internal structures */
            status = ENDAT3_ERR_INVALID_INPUT;
        }
    }

    if(status == ENDAT3_SUCCESS)
    {
        /* Validate params */
        if((params->pruicss_handle == NULL) ||
           (params->pruicss_handle->hwAttrs == NULL))
        {
            status = ENDAT3_ERR_INVALID_INPUT;
        }

        /* Validate all attrs members */
        if((attrs->instance >= gEndat3ConfigNum) ||
            (attrs->mode > ENDAT3_MODE_SINGLE_CHANNEL_SINGLE_PRU) ||
            (attrs->pruicss_instance > 1) ||
            (attrs->pruicss_slice > 1) ||
            (attrs->channel_mask == 0) ||
            (attrs->channel_mask > 0x7) ||
            (attrs->channel0_enabled > 1) ||
            (attrs->channel1_enabled > 1) ||
            (attrs->channel2_enabled > 1) ||
            (attrs->total_channels == 0) ||
            (attrs->total_channels > 3) ||
            (attrs->core_clk_freq == 0) ||
            (attrs->iep_clk_freq == 0) ||
            (attrs->iep_instance > 1) ||
            (attrs->iep_cmp_event >= ENDAT3_IEP_MAX_CMP_EVENT) ||
            (attrs->iep_cap_event >= ENDAT3_IEP_MAX_CAP_EVENT) ||
            (attrs->iep_base_addr == NULL))
        {
            status = ENDAT3_ERR_INVALID_INPUT;
        }

        /* Validate baud_rate - must be one of the supported EnDAT3 modes */
        if((attrs->baud_rate != ENDAT3_BAUD_RATE_12_5_MBPS))
        {
            status = ENDAT3_ERR_INVALID_INPUT;
        }

        /* Validate core_clk_freq - must be one of the supported EnDAT3 frequencies */
        if((attrs->core_clk_freq != ENDAT3_CORE_CLK_200MHZ) && (attrs->core_clk_freq != ENDAT3_CORE_CLK_300MHZ))
        {
            status = ENDAT3_ERR_INVALID_INPUT;
        }
    }

    if(status == ENDAT3_SUCCESS)
    {
        priv->pruicss_handle = params->pruicss_handle;

        /* Set base memory address based on PRU slice */
        if(attrs->pruicss_slice)
        {
            priv->base_mem_addr = (uint32_t *)(((PRUICSS_HwAttrs *)(priv->pruicss_handle->hwAttrs))->pru1DramBase);
        }
        else
        {
            priv->base_mem_addr = (uint32_t *)(((PRUICSS_HwAttrs *)(priv->pruicss_handle->hwAttrs))->pru0DramBase);
        }

        priv->endat3_interface = (endat3_interface *)(priv->base_mem_addr);

        endat3_generate_memory_image(handle);

        /* Set delay cycles based on PRU frequency */
        status = endat3_set_delay_cycles(handle);
    }

    if(status == ENDAT3_SUCCESS)
    {
        /*Set IEP base address */
        base_addr = (void *)((PRUICSS_HwAttrs *)(handle->priv->pruicss_handle->hwAttrs))->baseAddr;
        temp = ((uint32_t)attrs->iep_base_addr) - ((uint32_t)base_addr);

        /* Initialize IEP base address in endat3_interface */
        status = endat3_config_iep_base_address(handle, temp);
    }

    if(status == ENDAT3_SUCCESS)
    {
        status = endat3_config_iep_cmp_event(handle, attrs->iep_cmp_event);
    }

    if(status == ENDAT3_SUCCESS)
    {
        status = endat3_config_iep_cap_event(handle, attrs->iep_cap_event);
    }

    if(status == ENDAT3_SUCCESS)
    {
        /* Set channel mask */
        status = endat3_set_channel_mask(handle, attrs->channel_mask);
    }

    if(status == ENDAT3_SUCCESS)
    {
        /* Configure EnDAT mode */
        if(PRUICSS_setGpMuxSelect(priv->pruicss_handle, attrs->pruicss_slice, PRUICSS_GP_MUX_SEL_MODE_ENDAT) != SystemP_SUCCESS)
        {
            status = ENDAT3_ERR_INVALID_INPUT;
        }
    }

    if(status == ENDAT3_SUCCESS)
    {
        /* Clear CFG0 registers for enabled channels */
        status = endat3_config_clr_cfg0(handle);
    }

    if(status == ENDAT3_SUCCESS)
    {
        status = endat3_calculate_clock(handle, &clk_cfg);
    }

    if(status == ENDAT3_SUCCESS)
    {
        status = endat3_config_clock(handle, &clk_cfg);
    }

    if(status == ENDAT3_SUCCESS)
    {
        status = endat3_set_operating_mode(handle, ENDAT3_OPMODE_HOST_TRIGGER);
    }

    if(status == ENDAT3_SUCCESS)
    {
        /* Mark handle as open after successful initialization */
        priv->is_open = 1;
    }
    else
    {
        handle = NULL;
    }

    return handle;
}

void endat3_deinit(endat3_handle handle)
{
    endat3_priv *priv;

    if((handle == NULL) || (handle->priv == NULL))
    {
        return;
    }

    priv = handle->priv;
    /* Mark as closed */
    priv->is_open = 0;
}

const endat3_attrs* endat3_get_attrs(endat3_handle handle)
{
    if((handle == NULL) || (handle->attrs == NULL))
    {
        return NULL;
    }

    return handle->attrs;
}

endat3_priv* endat3_get_priv(endat3_handle handle)
{
    if((handle == NULL) || (handle->priv == NULL))
    {
        return NULL;
    }

    return handle->priv;
}

/**
 * \brief Calculate clock configuration parameters for EnDAT3 communication
 *
 * \details Computes TX and RX clock divisors based on target baud rate and core clock frequency.
 *          Configures oversampling, start bit polarity, and fractional divider if needed.
 *          Always uses core clock (not UART clock) for EnDAT3 communication.
 *
 * \param handle      EnDAT3 handle
 * \param clk_cfg Pointer to clock configuration structure to be populated
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle or clk_cfg is NULL
 *
 * \note Validation: Handle and clk_cfg pointer are validated
 * \note Clock calculations:
 *       - For 12.5 Mbps: TX=25MHz, RX=100MHz (8x oversampling)
 *       - For 25 Mbps: NOT SUPPORTED (FIXME)
 */
static int32_t endat3_calculate_clock(endat3_handle handle, endat3_clock_config *clk_cfg)
{
    const endat3_attrs      *attrs;
    uint32_t                freq;

    attrs = handle->attrs;

    if(attrs->baud_rate == ENDAT3_BAUD_RATE_12_5_MBPS)
    {
        freq = ENDAT3_BAUD_RATE_12_5_MBPS_VALUE;
    }
    else
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    /* ENDAT3 always uses Core clock (no UART clock support) */
    /* For 8x oversampling, use value of 7. Use "0" as start bit for receive */
    clk_cfg->rx_div_attr = (ENDAT3_SB_POLARITY << 3) | (ENDAT3_OVERSAMPLE_RATE_8X - 1);

    /* For 12.5 Mbps, TX clock = 25 MHz, RX clock = 100 MHz */
    /* For   25 Mbps, TX clock = 50 MHz, RX clock = 200 MHz */

    clk_cfg->tx_div = (attrs->core_clk_freq / (freq * (ENDAT3_TX_CLOCK_MULTIPLIER))) - 1;
    clk_cfg->rx_div = (attrs->core_clk_freq / (freq * (ENDAT3_OVERSAMPLE_RATE_8X))) - 1;
    clk_cfg->is_core_clk = 1;  /* Always use core clock */

    return ENDAT3_SUCCESS;
}

/**
 * \brief Configure PRU-ICSS hardware clock registers for EnDAT3
 *
 * \details Writes calculated clock divisors to PRU-ICSS CFG registers for TX and RX clocks.
 *          Configures appropriate registers based on PRU slice (PRU0 or PRU1).
 *
 * \param handle       EnDAT3 handle
 * \param clk_cfg Pointer to clock configuration with calculated divisors
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle or clk_cfg is NULL
 *
 * \note Validation: Handle and clk_cfg pointer are validated
 * \note Hardware access: Writes to PRU-ICSS CFG registers (PRUx_ED_RX_CFG_REG, PRUx_ED_TX_CFG_REG)
 * \note PRU slice determines which register set (PRU0 or PRU1) is configured
 */
static int32_t endat3_config_clock(endat3_handle handle, endat3_clock_config *clk_cfg)
{
    endat3_priv             *priv;
    const endat3_attrs      *attrs;
    void                    *pruicss_cfg;
    uint32_t                rx_reg_val;
    uint32_t                tx_reg_val;

    priv = handle->priv;
    attrs = handle->attrs;
    pruicss_cfg = (void *)(((PRUICSS_HwAttrs *)(priv->pruicss_handle->hwAttrs))->cfgRegBase);

    /* Configure RX and TX CFG registers based on PRU slice */
    /* Polarity of Start bit is 0 for EnDAT3 */
    if(attrs->pruicss_slice)
    {
        /* Slice 1 - Read-Modify-Write for RX CFG */
        rx_reg_val = HW_RD_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG);
        /*
         * NOTE: Using CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MASK instead of
         * CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_MASK because of incorrect definition.
         */
        rx_reg_val &= ~(CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_MASK);
        rx_reg_val |= (clk_cfg->rx_div << CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_SHIFT) |
                      (clk_cfg->is_core_clk << CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_SHIFT) |
                      (clk_cfg->rx_div_attr);
        HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG, rx_reg_val);

        /* Slice 1 - Read-Modify-Write for TX CFG */
        tx_reg_val = HW_RD_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG);
        tx_reg_val &= ~(CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_MASK);
        tx_reg_val |= (clk_cfg->tx_div << CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_SHIFT) |
                      (clk_cfg->is_core_clk << CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_SHIFT);
        HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG, tx_reg_val);
    }
    else
    {
        /* Slice 0 - Read-Modify-Write for RX CFG */
        rx_reg_val = HW_RD_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG);
        rx_reg_val &= ~(CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_MASK);
        rx_reg_val |= (clk_cfg->rx_div << CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_SHIFT) |
                      (clk_cfg->is_core_clk << CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_SHIFT) |
                      (clk_cfg->rx_div_attr);
        HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG, rx_reg_val);

        /* Slice 0 - Read-Modify-Write for TX CFG */
        tx_reg_val = HW_RD_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG);
        tx_reg_val &= ~(CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_MASK |
                        CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_MASK);
        tx_reg_val |= (clk_cfg->tx_div << CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_SHIFT) |
                      (clk_cfg->is_core_clk << CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_SHIFT);
        HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG, tx_reg_val);
    }

    return ENDAT3_SUCCESS;
}


/* ========================================================================== */
/*                          Request/Response Handling                         */
/* ========================================================================== */

/**
 * \brief Prepare EnDAT3 request frames in TX buffer
 *
 * \details Constructs command and data frames in TX buffer with CRC calculation.
 *          Reverses byte order for transmission and validates buffer capacity.
 *
 * \param handle      EnDAT3 handle
 * \param cmd         Command byte to send
 * \param data_array  Pointer to array of data words (optional, can be NULL for command-only)
 * \param num_frames  Number of frames to send
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle is NULL, invalid frame count, or buffer overflow
 *
 * \note Validation: Handle, and frame count (1 to ENDAT3_MAX_TX_FRAMES), and data_array
 * \note Each frame is 4 bytes: command/data(1) + data(2) + CRC(1)
 * \note CRC is calculated for each frame independently using \ref endat3_calculate_crc()
 * \note Byte order is reversed for PRU firmware consumption
 */
static int32_t endat3_prepare_request(endat3_handle handle, uint8_t cmd, volatile uint32_t *data_array, uint8_t num_frames)
{
    endat3_priv *priv;
    uint8_t i, k;
    uint8_t temp;
    uint8_t frame_length;

    /* Buffer overflow protection - check against actual buffer capacity (6) */
    if(num_frames > ENDAT3_MAX_TX_FRAMES || num_frames == 0)
    {
        return ENDAT3_ERR_INVALID_INPUT;  /* Invalid frame count (must be 1-6) */
    }

    if(data_array == NULL)
    {
        return ENDAT3_ERR_INVALID_INPUT;  /* Invalid data array pointer */
    }

    priv = handle->priv;

    /* Process frames, each 4 bytes long */
    for(k = 0; k < num_frames; k++)
    {
        /* Create request frame */
        priv->endat3_interface->tx_buffer[k * 4 + 0] = cmd;                            /* Command code */
        priv->endat3_interface->tx_buffer[k * 4 + 1] = data_array[k] & 0xFF;           /* LSB of data[k] */
        priv->endat3_interface->tx_buffer[k * 4 + 2] = (data_array[k] >> 8) & 0xFF;    /* MSB of data[k] */
        priv->endat3_interface->tx_buffer[k * 4 + 3] = endat3_calculate_crc(priv->endat3_interface->tx_buffer + k * 4, 3);

        /* Reverse byte order of the entire buffer (4 bytes: cmd, LSB, MSB, CRC) */
        frame_length = ENDAT3_FRAME_SIZE_BYTES;  /* Total frame length: command(1) + data(2) + CRC(1) */

        /* Swap bytes from outside toward the center */
        for(i = 0; i < frame_length / 2; i++)
        {
            temp = priv->endat3_interface->tx_buffer[k * 4 + i];
            priv->endat3_interface->tx_buffer[k * 4 + i] = priv->endat3_interface->tx_buffer[k * 4 + frame_length - 1 - i];
            priv->endat3_interface->tx_buffer[k * 4 + frame_length - 1 - i] = temp;
        }
    }

    return ENDAT3_SUCCESS;
}

/**
 * \brief Wait for and check EnDAT3 reception completion status
 *
 * \details Checks encoder busy status flag to determine if reception is complete.
 *          Detects encoder errors and busy status during communication.
 *
 * \param handle EnDAT3 handle
 *
 * \retval ENDAT3_SUCCESS (0) if reception completed successfully
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle is NULL
 * \retval ENDAT3_ERR_BUSY (-2) if encoder is still busy (transfer in progress)
 * \retval ENDAT3_ERR_SAMPLING_ERROR (-7) if encoder detected an error condition
 *
 * \note Validation: Handle pointer is validated
 * \note Encoder status: Checks busy flag (ENCODER_IDLE/ENCODER_BUSY/ENCODER_ERROR)
 * \note Caller should poll this function until success or implement timeout handling
 */
static int32_t endat3_wait_rx_complete(endat3_handle handle)
{
    endat3_priv *priv;

    priv = handle->priv;

    /* Return sampling error if encoder detected an error condition */
    if(priv->endat3_interface->busy == ENCODER_ERROR)
    {
        return ENDAT3_ERR_SAMPLING_ERROR;
    }
    /* Return busy status while a transfer is still in progress */
    if(priv->endat3_interface->busy == ENCODER_BUSY)
    {
        return ENDAT3_ERR_BUSY;
    }
    return ENDAT3_SUCCESS;
}

/**
 * \brief Parse received EnDAT3 frames from RX buffer
 *
 * \details Extracts HPF (High Priority Frame), LPH (Low Priority Header), and LPF (Low Priority Frames)
 *          from raw RX buffer into structured format. Copies data, status, and CRC fields.
 *
 * \param handle        EnDAT3 handle
 * \param rx_buffer     Pointer to RX buffer containing received frames (size of RX buffer must be >= 20 bytes)
 *
 * \retval ENDAT3_SUCCESS (0) on successful frame parsing
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle/rx_buffer is NULL or buffer too small
 *
 * \note Assumption: rx buffer length >= ENDAT3_MIN_RX_BUFFER_SIZE(20)
 * \note Validation: Handle, and rx_buffer pointer
 * \note Does not validate CRC - caller must use \ref endat3_validate_crc() for each frame
 * \note On validation failure, does not modify interface structures
 */
static int32_t endat3_parse_frames(endat3_handle handle, volatile uint8_t *rx_buffer)
{
    endat3_priv *priv;
    uint8_t i, j;

    priv = handle->priv;
    /* Parse HPF (bytes 0-7) - byte-by-byte copy to preserve volatile semantics */
    for(i = 0; i < HPF_DATA_SIZE; i++)
    {
        priv->endat3_interface->hpf.data[i] = rx_buffer[i];
    }
    priv->endat3_interface->hpf.status = rx_buffer[6];
    priv->endat3_interface->hpf.crc = rx_buffer[7];

    /* Parse LPH (bytes 8-11) */
    priv->endat3_interface->lph.status = rx_buffer[8];
    priv->endat3_interface->lph.num_lpf = rx_buffer[9];
    priv->endat3_interface->lph.crc = rx_buffer[11];

    /* Parse LPF[0] (bytes 12-19) */
    priv->endat3_interface->lpf[0].status = rx_buffer[12];  /* Copy status byte */

    /* Copy data payload byte by byte */
    for(j = 0; j < LPF_DATA_SIZE; j++)
    {
        priv->endat3_interface->lpf[0].data[j] = rx_buffer[13 + j];
    }

    priv->endat3_interface->lpf[0].crc = rx_buffer[19];  /* Copy CRC byte */

    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                      Command send/receive APIs                             */
/* ========================================================================== */

int32_t endat3_send_command(endat3_handle handle, uint8_t cmd, uint8_t frames)
{
    endat3_priv *priv;
    int32_t status;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Prepare request frame */
    status = endat3_prepare_request(handle, cmd, priv->endat3_interface->bg_data, frames);

    if(status != ENDAT3_SUCCESS)
    {
        return status;
    }

    return ENDAT3_SUCCESS;
}

int32_t endat3_receive_response(endat3_handle handle)
{
    endat3_priv *priv;
    int32_t status;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Wait for RX complete */
    status = endat3_wait_rx_complete(handle);
    if(status != ENDAT3_SUCCESS)
    {
        return status;
    }

    /* Parse received frames */
    status = endat3_parse_frames(handle, priv->endat3_interface->rx_buffer);
    if(status != ENDAT3_SUCCESS)
    {
        return status;
    }

    /* HPF CRC check */
    status = endat3_validate_crc(priv->endat3_interface->rx_buffer + ENDAT3_HPF_OFFSET, ENDAT3_HPF_TOTAL_SIZE);
    if(status != ENDAT3_SUCCESS)
    {
        return ENDAT3_ERR_HPF_CRC_FAIL;
    }

    /* LPH CRC check */
    status = endat3_validate_crc(priv->endat3_interface->rx_buffer + ENDAT3_LPH_OFFSET, ENDAT3_LPH_TOTAL_SIZE);
    if(status != ENDAT3_SUCCESS)
    {
        return ENDAT3_ERR_LPH_CRC_FAIL;
    }

    /* check for SENDLIST 0 to calculate CRC for LPF only */
    if(priv->endat3_interface->tx_buffer[3] == 0)
    {
        /* LPF CRC check for SENDLIST 0 */
        status = endat3_validate_crc(priv->endat3_interface->rx_buffer + ENDAT3_LPF_OFFSET, ENDAT3_LPF_TOTAL_SIZE);
        if(status != ENDAT3_SUCCESS)
        {
            return ENDAT3_ERR_LPF_CRC_FAIL;
        }
    }

    return ENDAT3_SUCCESS;
}

/**
 * \brief Reflect (reverse) bits in a value
 *
 * \details Reverses the bit order of a value within the specified width.
 *          Used for CRC calculations that require bit reflection.
 *
 * \param value Value to reflect
 * \param width Number of bits to reflect (e.g., 8 for byte, 16 for word)
 *
 * \return Bit-reflected value
 */
static uint16_t endat3_reflect_general(uint16_t value, uint16_t width)
{
    uint16_t result = 0;
    uint16_t i;

    for(i = 0; i < width; i++)
    {
        if((value & (1 << i)) != 0)
        {
            result |= (1 << (width - 1 - i));
        }
    }
    return result;
}

/**
 * \brief Generic CRC computation with configurable parameters
 *
 * \details Computes CRC using customizable polynomial, width, initial value, and reflection options.
 *
 * \param bytes           Input data buffer
 * \param length          Number of bytes to process
 * \param poly            CRC polynomial
 * \param crcsize         CRC width in bits
 * \param initialValue    Initial CRC register value
 * \param inputReflected  1 to reflect input bytes, 0 otherwise
 * \param resultReflected 1 to reflect final CRC, 0 otherwise
 * \param finalXor        Value to XOR with final CRC
 *
 * \return Computed CRC value
 */
static uint16_t endat3_compute_crc(const volatile uint8_t *bytes, size_t length,
                          uint16_t poly, uint16_t crcsize,
                          uint16_t initialValue, uint8_t inputReflected,
                          uint8_t resultReflected, uint16_t finalXor)
{
    /* Calculate bit manipulation constants */
    uint16_t bits_to_shift = crcsize - 8;       /* How many bits to shift input byte */
    uint16_t bit_mask = 1 << (crcsize - 1);     /* Mask for MSB check */
    uint16_t final_mask = (1 << crcsize) - 1;   /* Mask for final value */
    uint16_t crc = initialValue;
    size_t j;
    uint16_t i;
    uint8_t cur_byte;

    /* Process each input byte */
    for(j = 0; j < length; j++)
    {
        /* Reflect input byte if needed */
        cur_byte = inputReflected ? (uint8_t)endat3_reflect_general(bytes[j], 8) : bytes[j];

        /* XOR the byte into the MSB of CRC register */
        crc ^= (uint16_t)(cur_byte << bits_to_shift);

        /* Process each bit */
        for(i = 0; i < 8; i++)
        {
            if((crc & bit_mask) != 0)
            {
                /* MSB is set, shift left and XOR with polynomial */
                crc = (uint16_t)((crc << 1) ^ poly);
            }
            else
            {
                /* MSB not set, just shift left */
                crc <<= 1;
            }
        }

        /* Apply final mask to keep only relevant bits */
        crc = crc & final_mask;
    }

    /* Reflect result if needed */
    if(resultReflected)
    {
        crc = endat3_reflect_general(crc, crcsize);
    }

    /* Apply final XOR */
    crc ^= finalXor;

    return crc & final_mask;
}

/**
 * \brief Calculate EnDAT3 protocol-specific CRC-8
 *
 * \details Computes CRC-8 for EnDAT3 protocol using fixed parameters:
 *          polynomial=0xA7, initial=0xFF, input/result reflected, finalXor=0x00.
 *          This is a wrapper around \ref endat3_compute_crc() with EnDAT3-specific settings.
 *
 * \param data Pointer to input data buffer
 * \param len  Number of bytes to process
 *
 * \return 8-bit CRC value
 */
static uint8_t endat3_calculate_crc(const volatile uint8_t *data, uint32_t len)
{
    /* CRC parameters: polynomial=0xA7, crcsize=8, initialValue=0xFF,
     * inputReflected=1, resultReflected=1, finalXor=0x00 */
    return ((uint8_t)endat3_compute_crc(data, len, 0xA7, 8, 0xFF, 1, 1, 0x00));
}

/**
 * \brief Validate CRC of received EnDAT3 frame
 *
 * \details Extracts CRC from last byte of buffer, recalculates CRC for data bytes,
 *          and compares for integrity verification. Returns generic error on mismatch
 *          so caller can set specific error context (HPF/LPH/LPF).
 *
 * \param buffer Pointer to frame buffer (data + CRC byte)
 * \param length Total frame length including CRC byte (must be >= 2)
 *
 * \retval ENDAT3_SUCCESS (0) if CRC matches (frame valid)
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if buffer length < 2
 * \retval ENDAT3_ERR_RX_FAIL (-3) if CRC mismatch (caller should set specific error)
 *
 * \note Assumption: buffer is a valid pointer and not NULL
 * \note Validation: Frame length must be >= 2 (at least 1 data byte + 1 CRC byte)
 * \note CRC calculation: Uses \ref endat3_calculate_crc() on all bytes except last
 * \note Generic error: Returns ENDAT3_ERR_RX_FAIL on CRC failure, not frame-specific error
 */
static int32_t endat3_validate_crc(const volatile uint8_t *buffer, uint32_t length)
{
    uint8_t received_crc;
    uint8_t calculated_crc;

    /* A valid frame must contain at least one data byte and a CRC byte */
    if(length <= 1)
    {
        return ENDAT3_ERR_INVALID_INPUT;  /* Invalid frame length */
    }

    received_crc = buffer[length - 1];
    calculated_crc = endat3_calculate_crc(buffer, length - 1);

    /* Return generic error - caller sets specific CRC error context (HPF/LPH/LPF) */
    return ((received_crc == calculated_crc) ? ENDAT3_SUCCESS : ENDAT3_ERR_RX_FAIL);
}

/**
 * \brief Clear CFG0 registers for enabled EnDAT3 channels
 *
 * \details Clears (writes 0) to PRU-ICSS CFG0 registers for all enabled channels.
 *          CFG0 registers control channel-specific configuration and must be cleared
 *          before initializing EnDAT3 communication.
 *
 * \param handle EnDAT3 handle
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle is NULL
 *
 * \note Validation: Handle pointer is validated
 * \note Hardware access: Clears PRUx_ED_CHy_CFG0_REG for each enabled channel
 * \note PRU slice determines which register set (PRU0 or PRU1) is accessed
 */
static int32_t endat3_config_clr_cfg0(endat3_handle handle)
{
    endat3_priv         *priv;
    const endat3_attrs  *attrs;
    void                *pruicss_cfg;

    priv = handle->priv;
    attrs = handle->attrs;
    pruicss_cfg = (void *)(((PRUICSS_HwAttrs *)(priv->pruicss_handle->hwAttrs))->cfgRegBase);

    if(attrs->pruicss_slice)
    {
        if(attrs->channel0_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_CH0_CFG0_REG, 0);
        }
        if(attrs->channel1_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_CH1_CFG0_REG, 0);
        }
        if(attrs->channel2_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU1_ED_CH2_CFG0_REG, 0);
        }
    }
    else
    {
        if(attrs->channel0_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_CH0_CFG0_REG, 0);
        }
        if(attrs->channel1_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_CH1_CFG0_REG, 0);
        }
        if(attrs->channel2_enabled)
        {
            HW_WR_REG32((uint8_t *)pruicss_cfg + CSL_ICSS_PR1_CFG_SLV_PRU0_ED_CH2_CFG0_REG, 0);
        }
    }
    return ENDAT3_SUCCESS;
}

/**
 * \brief Calculate and set timing delay cycles for EnDAT3 communication
 *
 * \details Scales reference delay values based on actual PRU core clock frequency.
 *          Computes delays for TX start, RX start, propagation time measurement, and CRC calculation.
 *          All reference delays are defined for 1MHz base frequency and scaled to actual frequency.
 *
 * \param handle EnDAT3 handle
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle is NULL
 *
 * \note Validation: Handle pointer is validated
 * \note Scaling formula: actual_cycles = (reference_cycles * actual_freq) / 1MHz
 * \note Delay types: TX start delays, RX start delays, propagation time delays, CRC delays
 */
static int32_t endat3_set_delay_cycles(endat3_handle handle)
{
    endat3_priv         *priv;
    uint64_t            core_clk_freq;

    priv = handle->priv;
    core_clk_freq = handle->attrs->core_clk_freq;
    /* Scale delay values based on actual PRU frequency relative to 1MHz reference.
     * Formula: actual_cycles = (reference_cycles * actual_freq) / reference_freq
     * Reference values are defined as macros and represent cycles at 1MHz base frequency.
     *
     * 64-bit arithmetic prevents overflow: Cast to uint64_t ensures safe intermediate result before division scales back to uint32_t range
     */

    priv->endat3_interface->delay_tx_start_1    = (uint32_t)(((uint64_t)ENDAT3_TX_START_DELAY_1_REF_CYCLES * core_clk_freq) / REFERENCE_PRU_FREQ_HZ);
    priv->endat3_interface->delay_tx_start_2    = (uint32_t)(((uint64_t)ENDAT3_TX_START_DELAY_2_REF_CYCLES * core_clk_freq) / REFERENCE_PRU_FREQ_HZ);
    priv->endat3_interface->delay_tx_start_3    = (uint32_t)(((uint64_t)ENDAT3_TX_START_DELAY_3_REF_CYCLES * core_clk_freq) / REFERENCE_PRU_FREQ_HZ);
    priv->endat3_interface->delay_10ms          = (uint32_t)(((uint64_t)ENDAT3_DELAY_10MS_REF_CYCLES * core_clk_freq) / REFERENCE_PRU_FREQ_HZ);

    priv->endat3_interface->delay_sampling      = (uint32_t)(core_clk_freq / REFERENCE_PRU_FREQ_HZ_FOR_SAMPLING);

    return ENDAT3_SUCCESS;
}

/**
 * \brief Set channel enable mask for EnDAT3 communication
 *
 * \details Configures which encoder channels (0-2) are enabled for communication.
 *          The mask is written to firmware interface structure for PRU firmware to use.
 *
 * \param handle       EnDAT3 handle
 * \param channel_mask Channel enable mask (bit 0=CH0, bit 1=CH1, bit 2=CH2)
 *
 * \retval ENDAT3_SUCCESS (0) on success
 * \retval ENDAT3_ERR_INVALID_INPUT (-1) if handle is NULL or channel_mask is not in required range
 */
static int32_t endat3_set_channel_mask(endat3_handle handle, uint8_t channel_mask)
{
    endat3_priv *priv;

    if((channel_mask == 0) || (channel_mask > ENDAT3_CHANNEL_MASK_MAX))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Set channel enable mask in firmware interface structure
     * Bit 0: Channel 0 enable
     * Bit 1: Channel 1 enable
     * Bit 2: Channel 2 enable
     */
    priv->endat3_interface->channel_enable_mask = channel_mask;

    return ENDAT3_SUCCESS;
}

int32_t endat3_handle_background_command_request(endat3_handle handle, const endat3_bg_cmd_params *params, uint8_t *mode, const char **acc_level_desc)
{
    endat3_priv *priv;
    uint8_t     index;
    uint8_t     frame_cnt;
    uint8_t     op_code;
    uint32_t    addr_msb;
    uint32_t    addr_lsb;
    uint32_t    data;
    uint8_t     mode_val = 0;
    const char  *acc_level_desc_val = NULL;
    uint8_t     acclevel;

    /* Validate handle, parameters, and internal structure pointers */
    /* Validate index bounds (bg_data array has 6 elements, each command uses 4 indices starting at index) */

    if((handle == NULL) || (params == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL) || (params->index >= ENDAT3_MAX_BG_CMD_INDEX))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Extract parameters from struct */
    index = params->index;
    frame_cnt = params->frame_cnt;
    op_code = params->op_code;
    addr_msb = params->addr_msb;
    addr_lsb = params->addr_lsb;
    data = params->data;

    switch(op_code)
    {
        case ENDAT3_BGREQ_NOP:
            /* NOP operation: Just need to send arbitrary data */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFFFF;              /* Arbitrary data */
            priv->endat3_interface->bg_data[index + 1] = (data >> 16) & 0xFFFF;       /* Arbitrary data */
            priv->endat3_interface->bg_data[index + 2] = (ENDAT3_BGREQ_NOP << 8);         /* OpCode */
            break;

        case ENDAT3_BGREQ_READ:
            /* READ operation: addr_msb = address[23:16], addr_lsb = address[15:0], data = num_words */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFF;                                          /* num_words */
            priv->endat3_interface->bg_data[index + 1] = addr_lsb & 0xFFFF;                                    /* address[15:0] */
            priv->endat3_interface->bg_data[index + 2] = (addr_msb & 0xFF) | (ENDAT3_BGREQ_READ << 8);        /* OpCode + address[23:16] */
            break;

        case ENDAT3_BGREQ_WRITE:
            /* WRITE operation: addr_msb = address[23:16], addr_lsb = address[15:0], data = value to write */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFFFF;                                        /* Word to write */
            priv->endat3_interface->bg_data[index + 1] = addr_lsb & 0xFFFF;                                    /* address[15:0] */
            priv->endat3_interface->bg_data[index + 2] = (addr_msb & 0xFF) | (ENDAT3_BGREQ_WRITE << 8);       /* OpCode + address[23:16] */
            break;

        case ENDAT3_BGREQ_RECONFIGURE:
            /* RECONFIGURE operation: Simply sends the reconfigure command */
            priv->endat3_interface->bg_data[index + 0] = 0x0000;                       /* Reserved (0) */
            priv->endat3_interface->bg_data[index + 1] = 0x0000;                       /* Reserved (0) */
            priv->endat3_interface->bg_data[index + 2] = ENDAT3_BGREQ_RECONFIGURE << 8;  /* OpCode */
            break;

        case ENDAT3_BGREQ_AUTH:
            /* AUTH operation: addr_msb = usrlevel, addr_lsb/data = password */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFFFF;                                  /* Password part 2 */
            priv->endat3_interface->bg_data[index + 1] = addr_lsb & 0xFFFF;                              /* Password part 1 */
            priv->endat3_interface->bg_data[index + 2] = (addr_msb & 0xFF) | (ENDAT3_BGREQ_AUTH << 8);  /* OpCode + User level */
            break;

        case ENDAT3_BGREQ_PROTECT:
        {
            /*
             * PROTECT operation with 2-byte bg_data entries:
             * bg_data[index+0]: Bytes 0-1 (acclevel, mode)
             * bg_data[index+1]: Bytes 2-3 (address[15:0])
             * bg_data[index+2]: Bytes 4-5 (address[23:16], OpCode=0x81)
             */
            mode_val = (data >> 24) & 0xFF;
            acclevel = (data >> 16) & 0xFF;

            /* Pack the first 2 bytes: acclevel (byte 0) and mode (byte 1) */
            priv->endat3_interface->bg_data[index + 0] = (mode_val << 8) | acclevel;

            /* Pack the middle 2 bytes: address[15:0] (bytes 2-3) */
            priv->endat3_interface->bg_data[index + 1] = addr_lsb & 0xFFFF;

            /* Pack the last 2 bytes: address[23:16] (byte 4) and OpCode=0x81 (byte 5) */
            priv->endat3_interface->bg_data[index + 2] = (0x81 << 8) | (addr_msb & 0xFF);

            /* Get description for access level */
            switch(acclevel)
            {
                case 0:
                    acc_level_desc_val = "USER";
                    break;
                case 1:
                    acc_level_desc_val = "OEM2";
                    break;
                case 2:
                    acc_level_desc_val = "OEM1";
                    break;
                case 3:
                    acc_level_desc_val = "MANUFACTURER";
                    break;
                default:
                    acc_level_desc_val = "Unknown";
                    break;
            }

            break;
        }

        case ENDAT3_BGREQ_SETPASS:
            /* SETPASS operation: addr_msb = usrlevel, addr_lsb/data = password */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFFFF;                                     /* Password part 2 */
            priv->endat3_interface->bg_data[index + 1] = addr_lsb & 0xFFFF;                                 /* Password part 1 */
            priv->endat3_interface->bg_data[index + 2] = (addr_msb & 0xFF) | (ENDAT3_BGREQ_SETPASS << 8);  /* OpCode + User level */
            break;

        case ENDAT3_BGREQ_LOCATE:
            /* LOCATE operation: addr_msb = not used, addr_lsb = not used, data = ctrl */
            priv->endat3_interface->bg_data[index + 0] = data & 0xFF;                  /* ctrl */
            priv->endat3_interface->bg_data[index + 1] = 0x0000;                       /* Reserved (0) */
            priv->endat3_interface->bg_data[index + 2] = ENDAT3_BGREQ_LOCATE << 8;     /* OpCode */
            break;

        default:
            /* Invalid operation code, use NOP */
            priv->endat3_interface->bg_data[index + 0] = 0x0000;               /* Arbitrary data */
            priv->endat3_interface->bg_data[index + 1] = 0x0000;               /* Arbitrary data */
            priv->endat3_interface->bg_data[index + 2] = ENDAT3_BGREQ_NOP << 8;  /* OpCode */
            break;
    }

    /* BG_DATAT=0 for last frame in which we receive BG response in LPFs */
    priv->endat3_interface->bg_data[index + 3] = 0x0;
    /* Set the frame count for all operations */
    priv->endat3_interface->expected_tx_frames_count = frame_cnt;
    if(op_code == ENDAT3_BGREQ_RECONFIGURE)
    {
        priv->endat3_interface->expected_tx_frames_count++;
    }
    /* Populate output parameters if provided */
    if(mode != NULL)
    {
        *mode = mode_val;
    }
    if(acc_level_desc != NULL)
    {
        *acc_level_desc = acc_level_desc_val;
    }

    return ENDAT3_SUCCESS;
}

const char* endat3_get_error_description(endat3_error_code error_code)
{
    switch(error_code)
    {
        case ENDAT3_ERR_UNKNOWN:
            return "Unknown error cause";
        case ENDAT3_FGERR_RECONFIGURE:
            return "Device in configuration due to RECONFIGURE";
        case ENDAT3_FGERR_ECHO:
            return "ECHO response";
        case ENDAT3_FGERR_INVALID_FID:
            return "Invalid FID configured";
        case ENDAT3_FGERR_DUPLICATE_FID:
            return "FID selected multiple times in cycle";
        case ENDAT3_FGERR_INVALID_DATA:
            return "Invalid data delivered internally";
        case ENDAT3_FGERR_INT_TRM:
            return "LPF supported but unavailable (value not formed in time)";
        case ENDAT3_FGERR_NO_SENSOR_DATA:
            return "Sensor box data not available";
        case ENDAT3_BGERR_USAGE:
            return "Generic operator error";
        case ENDAT3_BGERR_USAGE_OPCODE:
            return "Invalid or unsupported command code";
        case ENDAT3_BGERR_USAGE_ARGUMENTS:
            return "Invalid arguments";
        case ENDAT3_BGERR_USAGE_SEQUENCE:
            return "Invalid command sequence";
        case ENDAT3_BGERR_USAGE_ACCESS_DENIED:
            return "Access denied; insufficient user level";
        case ENDAT3_BGERR_USAGE_MEM_ADDRESS:
            return "Access to invalid address";
        case ENDAT3_BGERR_USAGE_NO_BG:
            return "Encoder doesn't support background processing";
        case ENDAT3_BGERR_INTERNAL:
            return "Generic exception error in encoder";
        case ENDAT3_BGERR_INTERNAL_MEMORY:
            return "Exception error when accessing memory";
        case ENDAT3_BGERR_INTERNAL_CONFIG:
            return "Exception error: configuration invalid";
        default:
            if((error_code >= 0x0001) && (error_code <= 0x0FFF))
                return "Unknown foreground error";
            else if((error_code >= 0x1100) && (error_code <= 0x11FF))
                return "Unknown usage error";
            else if((error_code >= 0x1200) && (error_code <= 0x12FF))
                return "Unknown internal error";
            else
                return "Unrecognized error code";
    }
}

const char* endat3_get_error_action(endat3_error_code error_code)
{
    switch(error_code)
    {
        case ENDAT3_ERR_UNKNOWN:
            return "Try again";
        case ENDAT3_FGERR_RECONFIGURE:
            return "Try again after configuration completes";
        case ENDAT3_FGERR_ECHO:
            return "No action needed";
        case ENDAT3_FGERR_INVALID_FID:
        case ENDAT3_FGERR_DUPLICATE_FID:
        case ENDAT3_FGERR_NO_SENSOR_DATA:
        case ENDAT3_BGERR_USAGE:
        case ENDAT3_BGERR_USAGE_OPCODE:
        case ENDAT3_BGERR_USAGE_ARGUMENTS:
        case ENDAT3_BGERR_USAGE_SEQUENCE:
        case ENDAT3_BGERR_USAGE_MEM_ADDRESS:
        case ENDAT3_BGERR_USAGE_NO_BG:
            return "Correct the application";
        case ENDAT3_FGERR_INVALID_DATA:
        case ENDAT3_FGERR_INT_TRM:
        case ENDAT3_BGERR_INTERNAL:
        case ENDAT3_BGERR_INTERNAL_MEMORY:
        case ENDAT3_BGERR_INTERNAL_CONFIG:
            return "Try again";
        case ENDAT3_BGERR_USAGE_ACCESS_DENIED:
            return "Authenticate with proper level and try again";
        default:
            if((error_code >= 0x0001) && (error_code <= 0x0FFF))
                return "Refer to documentation or try again";
            else if((error_code >= 0x1100) && (error_code <= 0x11FF))
                return "Correct the application";
            else if((error_code >= 0x1200) && (error_code <= 0x12FF))
                return "Try again";
            else
                return "Treat as unknown error and try again";
    }
}

/* ========================================================================== */
/*                    HPF (High Priority Frame) Access APIs                   */
/* ========================================================================== */

int32_t endat3_get_hpf_status(endat3_handle handle, uint8_t *status)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (status == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *status = priv->endat3_interface->hpf.status;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_hpf_data(endat3_handle handle, uint8_t *data)
{
    endat3_priv *priv;
    uint8_t     i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Manual copy instead of memcpy - more explicit and returns bytes copied */
    for(i = 0; i < HPF_DATA_SIZE; i++)
    {
        data[i] = priv->endat3_interface->hpf.data[i];
    }

    return HPF_DATA_SIZE;  /* Return number of bytes copied */
}

int32_t endat3_get_hpf_crc(endat3_handle handle, uint8_t *crc)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (crc == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *crc = priv->endat3_interface->hpf.crc;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_hpf_data_64_bit(endat3_handle handle, uint64_t *data)
{
    endat3_priv *priv;
    uint64_t result = 0;
    volatile uint8_t *hpf_data;
    uint8_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    hpf_data = priv->endat3_interface->hpf.data;

    /* Pack 6 bytes into uint64_t (little-endian) */
    for(i = 0; i < HPF_DATA_SIZE; i++)
    {
        result |= ((uint64_t)hpf_data[i]) << (i * 8);
    }

    *data = result;
    return ENDAT3_SUCCESS;
}

int32_t endat3_is_hpf_data_valid(endat3_handle handle, uint8_t *is_valid)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (is_valid == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *is_valid = (priv->endat3_interface->hpf.status & ENDAT3_HPF_STATUS_HPFV) != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_has_hpf_error(endat3_handle handle, uint8_t *has_error)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (has_error == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *has_error = (priv->endat3_interface->hpf.status & ENDAT3_HPF_STATUS_F) != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_has_hpf_warning(endat3_handle handle, uint8_t *has_warning)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (has_warning == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *has_warning = (priv->endat3_interface->hpf.status & ENDAT3_HPF_STATUS_W) != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_has_absolute_value(endat3_handle handle, uint8_t *has_absolute)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (has_absolute == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *has_absolute = (priv->endat3_interface->hpf.status & ENDAT3_HPF_STATUS_RM) != 0;
    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                    LPH (Low Priority Header) Access APIs                   */
/* ========================================================================== */

int32_t endat3_get_lph_status(endat3_handle handle, uint8_t *status)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (status == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *status = priv->endat3_interface->lph.status;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lph_lpf_count(endat3_handle handle, uint8_t *num_lpf)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (num_lpf == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *num_lpf = priv->endat3_interface->lph.num_lpf;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lph_crc(endat3_handle handle, uint8_t *crc)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (crc == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *crc = priv->endat3_interface->lph.crc;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lph_state(endat3_handle handle, endat3_lph_status *state)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (state == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *state = (endat3_lph_status)(priv->endat3_interface->lph.status & ENDAT3_LPH_STATE_MASK);
    return ENDAT3_SUCCESS;
}

int32_t endat3_has_bg_error(endat3_handle handle, uint8_t *has_error)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (has_error == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *has_error = (priv->endat3_interface->lph.status & ENDAT3_LPH_BG_ERR_EXEC) != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_is_bg_busy(endat3_handle handle, uint8_t *is_busy)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (is_busy == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *is_busy = (priv->endat3_interface->lph.status & ENDAT3_LPH_BG_BUSY) != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_has_bg_rtx_error(endat3_handle handle, uint8_t *has_error)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (has_error == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *has_error = (priv->endat3_interface->lph.status & ENDAT3_LPH_BG_RTX_ERROR) != 0;
    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                    LPF (Low Priority Frame) Access APIs                    */
/* ========================================================================== */

int32_t endat3_get_lpf_status(endat3_handle handle, uint8_t index, uint8_t *status)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (status == NULL) || (index >= MAX_LPF_COUNT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *status = priv->endat3_interface->lpf[index].status;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lpf_data(endat3_handle handle, uint8_t index, uint8_t *data)
{
    endat3_priv *priv;
    uint8_t     i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (index >= MAX_LPF_COUNT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Manual copy instead of memcpy - more explicit and returns bytes copied */
    for(i = 0; i < LPF_DATA_SIZE; i++)
    {
        data[i] = priv->endat3_interface->lpf[index].data[i];
    }

    return LPF_DATA_SIZE;  /* Return number of bytes copied */
}

int32_t endat3_get_lpf_crc(endat3_handle handle, uint8_t index, uint8_t *crc)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (crc == NULL) || (index >= MAX_LPF_COUNT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *crc = priv->endat3_interface->lpf[index].crc;
    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lpf_fid(endat3_handle handle, uint8_t index, uint8_t *fid)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (fid == NULL) || (index >= MAX_LPF_COUNT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* FID is typically in the status byte */
    *fid = priv->endat3_interface->lpf[index].status;
    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                    Communication Control APIs                              */
/* ========================================================================== */

int32_t endat3_is_connected(endat3_handle handle, uint8_t *is_connected)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (is_connected == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *is_connected = priv->endat3_interface->connected != 0;
    return ENDAT3_SUCCESS;
}

int32_t endat3_is_busy(endat3_handle handle, uint8_t *is_busy)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (is_busy == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *is_busy = (priv->endat3_interface->busy == ENCODER_BUSY);
    return ENDAT3_SUCCESS;
}

int32_t endat3_set_busy(endat3_handle handle, uint8_t busy)
{
    endat3_priv *priv;

    /* Validate parameters and internal structure pointers */
    if((handle == NULL) || (busy > 1) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->busy = busy;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_expected_tx_frame_count(endat3_handle handle, uint32_t *count)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (count == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *count = priv->endat3_interface->expected_tx_frames_count;
    return ENDAT3_SUCCESS;
}

int32_t endat3_set_expected_tx_frame_count(endat3_handle handle, uint32_t count)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->expected_tx_frames_count = count;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_propagation_time(endat3_handle handle, uint32_t *prop_time)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (prop_time == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *prop_time = priv->endat3_interface->propagation_time;
    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                    Command and Data APIs                                   */
/* ========================================================================== */

int32_t endat3_get_foreground_op_code(endat3_handle handle, uint32_t *opcode)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (opcode == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *opcode = priv->endat3_interface->foreground_op_code;
    return ENDAT3_SUCCESS;
}

int32_t endat3_set_foreground_op_code(endat3_handle handle, uint32_t opcode)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->foreground_op_code = opcode;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_background_op_code(endat3_handle handle, uint32_t *opcode)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (opcode == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *opcode = priv->endat3_interface->background_op_code;
    return ENDAT3_SUCCESS;
}

int32_t endat3_set_background_op_code(endat3_handle handle, uint32_t opcode)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->background_op_code = opcode;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_bg_data(endat3_handle handle, uint8_t index, uint32_t *data)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (index >= BG_DATA_SIZE) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *data = priv->endat3_interface->bg_data[index];
    return ENDAT3_SUCCESS;
}

int32_t endat3_set_bg_data(endat3_handle handle, uint8_t index, uint32_t data)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (index >= BG_DATA_SIZE) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->bg_data[index] = data;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_all_bg_data(endat3_handle handle, uint32_t *data)
{
    endat3_priv *priv;
    uint32_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy element by element to preserve volatile semantics */
    for(i = 0; i < (sizeof(priv->endat3_interface->bg_data) / sizeof(uint32_t)); i++)
    {
        data[i] = priv->endat3_interface->bg_data[i];
    }

    return ENDAT3_SUCCESS;
}

int32_t endat3_set_all_bg_data(endat3_handle handle, const uint32_t *data)
{
    endat3_priv *priv;
    uint32_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy element by element to preserve volatile semantics */
    for(i = 0; i < (sizeof(priv->endat3_interface->bg_data) / sizeof(uint32_t)); i++)
    {
        priv->endat3_interface->bg_data[i] = data[i];
    }

    return ENDAT3_SUCCESS;
}

/* ========================================================================== */
/*                    Buffer Access APIs                                      */
/* ========================================================================== */

const volatile uint8_t* endat3_get_rx_buffer(endat3_handle handle)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return NULL;
    }

    priv = handle->priv;
    return priv->endat3_interface->rx_buffer;
}

const volatile uint8_t* endat3_get_tx_buffer(endat3_handle handle)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return NULL;
    }

    priv = handle->priv;
    return priv->endat3_interface->tx_buffer;
}

int32_t endat3_set_tx_buffer(endat3_handle handle, const uint8_t *data, uint32_t length)
{
    endat3_priv *priv;
    uint32_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (data == NULL) || (length == 0) || (length > TX_BUFFER_SIZE) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy byte by byte to preserve volatile semantics */
    for(i = 0; i < length; i++)
    {
        priv->endat3_interface->tx_buffer[i] = data[i];
    }

    return ((int32_t)length);
}

/* ========================================================================== */
/*                    Utility and Helper APIs                                 */
/* ========================================================================== */

int32_t endat3_get_hpf_frame(endat3_handle handle, endat3_hpf *hpf)
{
    endat3_priv *priv;
    uint8_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (hpf == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy field by field to preserve volatile semantics */
    for(i = 0; i < HPF_DATA_SIZE; i++)
    {
        hpf->data[i] = priv->endat3_interface->hpf.data[i];
    }
    hpf->status = priv->endat3_interface->hpf.status;
    hpf->crc = priv->endat3_interface->hpf.crc;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lph_frame(endat3_handle handle, endat3_lph *lph)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (lph == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy field by field to preserve volatile semantics */
    lph->status = priv->endat3_interface->lph.status;
    lph->num_lpf = priv->endat3_interface->lph.num_lpf;
    lph->reserved = priv->endat3_interface->lph.reserved;
    lph->crc = priv->endat3_interface->lph.crc;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_lpf_frame(endat3_handle handle, uint8_t index, endat3_lpf *lpf)
{
    endat3_priv *priv;
    uint8_t i;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (lpf == NULL) || (index >= MAX_LPF_COUNT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    /* Copy field by field to preserve volatile semantics */
    lpf->status = priv->endat3_interface->lpf[index].status;
    for(i = 0; i < LPF_DATA_SIZE; i++)
    {
        lpf->data[i] = priv->endat3_interface->lpf[index].data[i];
    }
    lpf->crc = priv->endat3_interface->lpf[index].crc;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_error_code(endat3_handle handle, endat3_error_code *error_code)
{
    endat3_priv *priv;
    uint32_t error_val = 0;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (error_code == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Check if HPFV bit is NOT set in HPF status (indicates error in HPF data) */
    if((priv->endat3_interface->hpf.status & ENDAT3_HPF_STATUS_HPFV) == 0)
    {
        /* Extract error code from HPF data bytes 0-1 */
        error_val = (priv->endat3_interface->hpf.data[1] << 8) |
                    priv->endat3_interface->hpf.data[0];

        *error_code = (endat3_error_code)error_val;
        return ENDAT3_SUCCESS;
    }

    /* Check if BG.ERR_EXEC bit is set in LPH status */
    if((priv->endat3_interface->lph.status & ENDAT3_LPH_BG_ERR_EXEC) == ENDAT3_LPH_BG_ERR_EXEC)
    {
        /* Extract error code from LPF[0] data bytes 0-1 */
        error_val = (priv->endat3_interface->lpf[0].data[1] << 8) |
                    priv->endat3_interface->lpf[0].data[0];

        *error_code = (endat3_error_code)error_val;
        return ENDAT3_SUCCESS;
    }

    *error_code = ENDAT3_ERR_UNKNOWN;
    return ENDAT3_SUCCESS;
}

endat3_interface* endat3_get_interface(endat3_handle handle)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return NULL;
    }

    priv = handle->priv;
    return priv->endat3_interface;
}

int32_t endat3_set_operating_mode(endat3_handle handle, uint8_t opmode)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL) || (opmode > ENDAT3_OPMODE_PERIODIC_CAP))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->opmode_config = opmode;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_operating_mode(endat3_handle handle, uint8_t *opmode)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (opmode == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *opmode = priv->endat3_interface->opmode_config;
    return ENDAT3_SUCCESS;
}

/**
 * \brief Configure IEP base address in PRU shared memory
 *
 * \param handle            EnDAT3 handle
 * \param iep_base_address  IEP base address offset from PRU-ICSS base
 *
 * \return ENDAT3_SUCCESS on success, ENDAT3_ERR_INVALID_INPUT on validation failure
 */
static int32_t endat3_config_iep_base_address(endat3_handle handle, uint32_t iep_base_address)
{
    endat3_priv *priv;

    if(iep_base_address == 0)
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Write IEP base address to firmware interface */
    priv->endat3_interface->iep_base_address = iep_base_address;

    return ENDAT3_SUCCESS;
}

int32_t endat3_config_iep_cap_event(endat3_handle handle, uint8_t event_num)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (event_num >= ENDAT3_IEP_MAX_CAP_EVENT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Update IEP CAP event configuration in PRU DMEM */
    priv->endat3_interface->trigger_params.iep_cap_event = event_num;

    /* Calculate and store CAP register address for periodic CAP mode */
    priv->endat3_interface->trigger_params.iep_capture_reg = priv->endat3_interface->iep_base_address + ENDAT3_CSL_ICSS_PR1_IEP0_SLV_CAP0_REG0 + (ENDAT3_8_BYTE_REG_OFFSET * event_num);

    /* CAP6 and CAP7 have 2 extra registers for fall capture values, add extra offset */
    /* CAP6 and CAP7 has 2 register bits each. So bit 8 needs to be used for CAP7. Only capture rise bits for CAP6 and CAP7 are used. */
    if(event_num > 6)
    {
        priv->endat3_interface->trigger_params.iep_cap_event += 1;
        priv->endat3_interface->trigger_params.iep_capture_reg += ENDAT3_8_BYTE_REG_OFFSET;
    }

    return ENDAT3_SUCCESS;
}

int32_t endat3_config_iep_cmp_event(endat3_handle handle, uint8_t event_num)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (event_num >= ENDAT3_IEP_MAX_CMP_EVENT) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;

    /* Update IEP CMP event configuration in PRU DMEM */
    priv->endat3_interface->trigger_params.iep_cmp_event = event_num;

    return ENDAT3_SUCCESS;
}

int32_t endat3_release_start_trigger(endat3_handle handle)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->start_trigger = 1;

    return ENDAT3_SUCCESS;
}

int32_t endat3_clear_start_trigger(endat3_handle handle)
{
    endat3_priv *priv;

    /* Validate handle and internal structure pointers */
    if((handle == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    priv->endat3_interface->start_trigger = 0;

    return ENDAT3_SUCCESS;
}

int32_t endat3_get_start_trigger_status(endat3_handle handle, uint8_t *trigger_status)
{
    endat3_priv *priv;

    /* Validate handle, parameters, and internal structure pointers */
    if((handle == NULL) || (trigger_status == NULL) || (handle->priv == NULL) || (handle->priv->endat3_interface == NULL))
    {
        return ENDAT3_ERR_INVALID_INPUT;
    }

    priv = handle->priv;
    *trigger_status = priv->endat3_interface->start_trigger;
    return ENDAT3_SUCCESS;
}
