#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am263px libs
	$(MAKE) -f makefile.am263px examples

clean: libs-clean examples-clean
scrub: libs-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px all
	@echo  $(MAKE) -s -f makefile.am263px clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px libs
	@echo  $(MAKE) -s -f makefile.am263px libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263px examples
	@echo  $(MAKE) -s -f makefile.am263px examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263px examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_bissc_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_endat_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_nikon_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_tamagawa_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_bissc_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_endat_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_nikon_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_tamagawa_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263px motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/bissc_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/endat_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/nikon_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/tamagawa_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/sfra/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/rtlibs/utilities/datalog/am263px-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_motorcontrol_bissc = motorcontrol_bissc_r5f.ti-arm-clang
BUILD_COMBO_motorcontrol_endat = motorcontrol_endat_r5f.ti-arm-clang
BUILD_COMBO_motorcontrol_nikon = motorcontrol_nikon_r5f.ti-arm-clang
BUILD_COMBO_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang
BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_motorcontrol_bissc) $(BUILD_COMBO_motorcontrol_endat) $(BUILD_COMBO_motorcontrol_nikon) $(BUILD_COMBO_motorcontrol_tamagawa) $(BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_motorcontrol_bissc):
	$(MAKE) -C source/position_sense/bissc -f makefile.am263px.$(subst motorcontrol_bissc_,,$@) all

$(BUILD_COMBO_motorcontrol_endat):
	$(MAKE) -C source/position_sense/endat -f makefile.am263px.$(subst motorcontrol_endat_,,$@) all

$(BUILD_COMBO_motorcontrol_nikon):
	$(MAKE) -C source/position_sense/nikon -f makefile.am263px.$(subst motorcontrol_nikon_,,$@) all

$(BUILD_COMBO_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263px.$(subst motorcontrol_tamagawa_,,$@) all

$(BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263px.$(subst motorcontrol_tamagawa_over_soc_uart_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_motorcontrol_bissc = motorcontrol_bissc_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_motorcontrol_endat = motorcontrol_endat_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_motorcontrol_nikon = motorcontrol_nikon_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_motorcontrol_bissc) $(BUILD_COMBO_CLEAN_motorcontrol_endat) $(BUILD_COMBO_CLEAN_motorcontrol_nikon) $(BUILD_COMBO_CLEAN_motorcontrol_tamagawa) $(BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_motorcontrol_bissc):
	$(MAKE) -C source/position_sense/bissc -f makefile.am263px.$(subst motorcontrol_bissc_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_motorcontrol_endat):
	$(MAKE) -C source/position_sense/endat -f makefile.am263px.$(subst motorcontrol_endat_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_motorcontrol_nikon):
	$(MAKE) -C source/position_sense/nikon -f makefile.am263px.$(subst motorcontrol_nikon_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263px.$(subst motorcontrol_tamagawa_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263px.$(subst motorcontrol_tamagawa_over_soc_uart_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_motorcontrol_bissc = motorcontrol_bissc_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_motorcontrol_endat = motorcontrol_endat_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_motorcontrol_nikon = motorcontrol_nikon_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_motorcontrol_bissc) $(BUILD_COMBO_SCRUB_motorcontrol_endat) $(BUILD_COMBO_SCRUB_motorcontrol_nikon) $(BUILD_COMBO_SCRUB_motorcontrol_tamagawa) $(BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_motorcontrol_bissc):
	$(MAKE) -C source/position_sense/bissc -f makefile.am263px.$(subst motorcontrol_bissc_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_motorcontrol_endat):
	$(MAKE) -C source/position_sense/endat -f makefile.am263px.$(subst motorcontrol_endat_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_motorcontrol_nikon):
	$(MAKE) -C source/position_sense/nikon -f makefile.am263px.$(subst motorcontrol_nikon_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263px.$(subst motorcontrol_tamagawa_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263px.$(subst motorcontrol_tamagawa_over_soc_uart_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/bissc_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/endat_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/nikon_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/sfra/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/rtlibs/utilities/datalog/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all

 tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile all

 tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/bissc_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/endat_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/nikon_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/sfra/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/rtlibs/utilities/datalog/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean

 tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile clean

 tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 dcl_df22_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_df22_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_df22_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_df22_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_df22/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_pi_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_pi_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_pi_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_pi_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/dcl/dcl_pi/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 bissc_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/bissc_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 endat_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/endat_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 nikon_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/nikon_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 tamagawa_diagnostic_single_channel_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 tamagawa_diagnostic_soc_uart_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sfralib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/sfra/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263px-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 transforms_test_am263px-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263px-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/transforms/transforms_test/am263px-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dlog4ch_lib_am263px-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/rtlibs/utilities/datalog/am263px-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 bissc_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/bissc/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 endat_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/endat/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 nikon_peripheral_interface_single_ch_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/nikon/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub

 tamagawa_single_channel_am263px-lp_icss_m0_pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru0_fw/ti-pru-cgt -f makefile scrub

 tamagawa_single_channel_am263px-lp_icss_m0_pru1_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263px-lp/icss_m0_pru1_fw/ti-pru-cgt -f makefile scrub


.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
