#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am263x libs
	$(MAKE) -f makefile.am263x examples

clean: libs-clean examples-clean
scrub: libs-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263x all
	@echo  $(MAKE) -s -f makefile.am263x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263x libs
	@echo  $(MAKE) -s -f makefile.am263x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am263x examples
	@echo  $(MAKE) -s -f makefile.am263x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am263x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263x motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang
	@echo  $(MAKE) -s -f makefile.am263x motorcontrol_tamagawa_r5f.ti-arm-clang
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am263x motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_clean
	@echo  $(MAKE) -s -f makefile.am263x motorcontrol_tamagawa_r5f.ti-arm-clang_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/position_sense/tamagawa_diagnostic/single_channel/am263x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/sfra/am263x-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C examples/utilities/datalog/am263x-cc/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C source/position_sense/tamagawa/firmware/single_channel/am263x-lp/icssm-pru0_fw/ti-pru-cgt [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang
BUILD_COMBO_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart) $(BUILD_COMBO_motorcontrol_tamagawa)

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263x.$(subst motorcontrol_tamagawa_over_soc_uart_,,$@) all

$(BUILD_COMBO_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263x.$(subst motorcontrol_tamagawa_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_clean
BUILD_COMBO_CLEAN_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart) $(BUILD_COMBO_CLEAN_motorcontrol_tamagawa)

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263x.$(subst motorcontrol_tamagawa_over_soc_uart_,,$(subst _clean,,$@)) clean

$(BUILD_COMBO_CLEAN_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263x.$(subst motorcontrol_tamagawa_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart = motorcontrol_tamagawa_over_soc_uart_r5f.ti-arm-clang_scrub_scrub
BUILD_COMBO_SCRUB_motorcontrol_tamagawa = motorcontrol_tamagawa_r5f.ti-arm-clang_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart) $(BUILD_COMBO_SCRUB_motorcontrol_tamagawa)

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_motorcontrol_tamagawa_over_soc_uart):
	$(MAKE) -C source/position_sense/tamagawa_over_soc_uart -f makefile.am263x.$(subst motorcontrol_tamagawa_over_soc_uart_,,$(subst _scrub,,$@)) scrub

$(BUILD_COMBO_SCRUB_motorcontrol_tamagawa):
	$(MAKE) -C source/position_sense/tamagawa -f makefile.am263x.$(subst motorcontrol_tamagawa_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_ALL += tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/sfra/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile all

 transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile all

 transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile all

 dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C examples/utilities/datalog/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile all

 tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263x-lp/icssm-pru0_fw/ti-pru-cgt -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL += tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt_clean
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/sfra/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C examples/utilities/datalog/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt_clean:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263x-lp/icssm-pru0_fw/ti-pru-cgt -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL += tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt_scrub
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 dcl_df22_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_df22_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_df22_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_df22_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_df22/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_pi_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_pi_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dcl_pi_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 dcl_pi_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/dcl/dcl_pi/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 tamagawa_diagnostic_soc_uart_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic_over_soc_uart/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 tamagawa_diagnostic_single_channel_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/position_sense/tamagawa_diagnostic/single_channel/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 sfralib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/sfra/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263x-cc_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/transforms/transforms_test/am263x-cc/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 transforms_test_am263x-lp_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 transforms_test_am263x-lp_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C examples/transforms/transforms_test/am263x-lp/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 dlog4ch_lib_am263x-cc_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C examples/utilities/datalog/am263x-cc/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 tamagawa_single_channel_am263x-lp_icssm-pru0_fw_ti-pru-cgt_scrub:
	$(MAKE) -C source/position_sense/tamagawa/firmware/single_channel/am263x-lp/icssm-pru0_fw/ti-pru-cgt -f makefile scrub


.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
