/*
 *  Copyright (C) 2024 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

int olmag_exp[100] = {14,
                      14,
                      13,
                      12,
                      11,
                      10,
                      9,
                      8,
                      8,
                      7,
                      6,
                      5,
                      4,
                      3,
                      3,
                      2,
                      1,
                      0,
                      0,
                      0,
                      -1,
                      -2,
                      -2,
                      -3,
                      -4,
                      -4,
                      -5,
                      -5,
                      -6,
                      -6,
                      -6,
                      -7,
                      -7,
                      -7,
                      -7,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -8,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9,
                      -9};

int olphase_exp[100] = {-86,
                        -85,
                        -85,
                        -85,
                        -84,
                        -84,
                        -83,
                        -82,
                        -82,
                        -81,
                        -80,
                        -79,
                        -78,
                        -77,
                        -75,
                        -74,
                        -72,
                        -71,
                        -69,
                        -67,
                        -65,
                        -62,
                        -60,
                        -58,
                        -55,
                        -52,
                        -49,
                        -47,
                        -44,
                        -41,
                        -38,
                        -35,
                        -33,
                        -30,
                        -28,
                        -26,
                        -23,
                        -21,
                        -20,
                        -18,
                        -16,
                        -15,
                        -13,
                        -12,
                        -11,
                        -10,
                        -9,
                        -9,
                        -8,
                        -7,
                        -7,
                        -6,
                        -6,
                        -6,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -5,
                        -6,
                        -6,
                        -6,
                        -7,
                        -8,
                        -8,
                        -9,
                        -10,
                        -11,
                        -12,
                        -13,
                        -14,
                        -16,
                        -17,
                        -19,
                        -21,
                        -23,
                        -26,
                        -28,
                        -31,
                        -35,
                        -38,
                        -42,
                        -47,
                        -52,
                        -57,
                        -63,
                        -70,
                        -77,
                        -85,
                        -94,
                        -104,
                        -115,
                        -127,
                        -141};
