/*
*  Copyright (C) 2024 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 /* ========================================================================== */
 /*                             Include Files                                  */
 /* ========================================================================== */
 #include <drivers/pruicss.h>

/* PRU1_ED_RX_CFG_REG */
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_MASK         CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_SHIFT        CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_RESETVAL     CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_MAX          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SAMPLE_SIZE_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_MASK              CSL_ICSS_M_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_SHIFT             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_RESETVAL          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_MAX               CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_SB_POL_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_MASK             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_SHIFT            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_RESETVAL         CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_MAX              CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_CLK_SEL_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_MASK     CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_SHIFT    CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_RESETVAL CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_MAX      CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_FRAC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_MASK          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_SHIFT         CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_RESETVAL      CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_MAX           CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_PRU1_ED_RX_DIV_FACTOR_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_RESETVAL                            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_RX_CFG_REG_RESETVAL

/* PRU1_ED_TX_CFG_REG */
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_MASK             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_SHIFT            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_RESETVAL         CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_MAX              CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_CLK_SEL_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_MASK                 CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_0_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_MASK                 CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_1_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_MASK                 CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_BUSY_2_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT0_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT1_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT2_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_MASK            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_SHIFT           CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_RESETVAL        CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_MAX             CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ENDAT_SHARE_EN_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_MASK     CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_SHIFT    CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_RESETVAL CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_MAX      CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_FRAC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_MASK          CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_SHIFT         CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_RESETVAL      CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_MAX           CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_PRU1_ED_TX_DIV_FACTOR_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_RESETVAL                            CSL_ICSS_M_PR1_CFG_SLV_PRU1_ED_TX_CFG_REG_RESETVAL

/* PRU0_ED_RX_CFG_REG */
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_MASK         CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_SHIFT        CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_RESETVAL     CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_MAX          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SAMPLE_SIZE_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MASK              CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_SHIFT             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_RESETVAL          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MAX               CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_SB_POL_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_MASK             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_SHIFT            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_RESETVAL         CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_MAX              CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_CLK_SEL_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_MASK     CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_SHIFT    CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_RESETVAL CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_MAX      CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_FRAC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_MASK          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_SHIFT         CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_RESETVAL      CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_MAX           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_PRU0_ED_RX_DIV_FACTOR_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_RESETVAL                            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_RX_CFG_REG_RESETVAL

/* PRU0_ED_TX_CFG_REG */
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_MASK             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_SHIFT            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_RESETVAL         CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_MAX              CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_CLK_SEL_RESETVAL

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_MASK                 CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_0_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_MASK                 CSL_ICSS_M_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_1_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_MASK                 CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_SHIFT                CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_RESETVAL             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_MAX                  CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_BUSY_2_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT0_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT1_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_MASK           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_SHIFT          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_RESETVAL       CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_MAX            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT2_CLK_SYNC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_MASK            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_SHIFT           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_RESETVAL        CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_MAX             CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ENDAT_SHARE_EN_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_MASK     CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_SHIFT    CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_RESETVAL CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_MAX      CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_FRAC_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_MASK          CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_MASK
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_SHIFT         CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_SHIFT
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_RESETVAL      CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_RESETVAL
#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_MAX           CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_PRU0_ED_TX_DIV_FACTOR_MAX

#define CSL_ICSS_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_RESETVAL                            CSL_ICSS_M_PR1_CFG_SLV_PRU0_ED_TX_CFG_REG_RESETVAL